import os

TEST_DATABASE_USER = os.getenv('TEST_DATABASE_USER')
TEST_DATABASE_HOST = os.getenv('TEST_DATABASE_HOST')
TEST_DATABASE_PORT = os.getenv('TEST_DATABASE_PORT')
TEST_DATABASE_NAME = os.getenv('TEST_DATABASE_NAME')
TEST_DATABASE_URL = f'postgresql+asyncpg://{TEST_DATABASE_USER}@{TEST_DATABASE_HOST}:' \
                    f'{TEST_DATABASE_PORT}/{TEST_DATABASE_NAME}'

TEST_USERS_BLACKLIST_NAME = 'test_users_blacklist_name'
