"""renamed id column to user_id

Revision ID: 818a5fdfb71c
Revises: 7cfaf6e46be3
Create Date: 2023-05-06 02:09:53.686810

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '818a5fdfb71c'
down_revision = '7cfaf6e46be3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute('ALTER TABLE public.user RENAME COLUMN id TO user_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute('ALTER TABLE public.user RENAME COLUMN user_id TO id')
