import os

DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PORT = 5432
DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_URL = f'postgresql+asyncpg://{DATABASE_USER}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = 6379
USERS_BLACKLIST_NAME = 'users_black_list'
